import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiActivity, FiArrowRight, FiCalendar, FiDollarSign, FiPlus, FiRefreshCw, FiSearch, FiUsers } from "react-icons/fi";
import toast from "react-hot-toast";
import { getAuctions } from "../api/auctionApi";
import AuctionStatusBadge from "../components/auction/AuctionStatusBadge";
import LoadingScreen from "../components/LoadingScreen";
import EmptyState from "../components/EmptyState";
import ErrorState from "../components/ErrorState";
import { useAuth } from "../context/AuthContext";

const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n||0));
const date=v=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export default function Auctions(){
 const {isAdmin}=useAuth(); const [auctions,setAuctions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[status,setStatus]=useState("all");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await getAuctions();setAuctions(r.auctions||[]);}catch(e){setError(e.response?.data?.message||"Unable to load auctions.");}finally{setLoading(false)}},[]); useEffect(()=>{load()},[load]);
 const filtered=auctions.filter(a=>(status==="all"||a.status===status)&&`${a.name} ${a.description||""}`.toLowerCase().includes(q.toLowerCase()));
 if(loading)return <LoadingScreen label="Loading auctions..."/>;
 return <div className="space-y-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-slate-500">Auction workspace</p><h1 className="mt-2 text-3xl font-black">Auctions</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Browse upcoming, live and completed cricket auctions.</p></div>{isAdmin&&<Link to="/admin/auctions/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white dark:bg-white dark:text-slate-950"><FiPlus/> Create auction</Link>}</div>
 <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900 sm:flex-row"><div className="relative flex-1"><FiSearch className="absolute left-3 top-3.5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search auctions..." className="w-full rounded-xl bg-slate-100 py-3 pl-10 pr-3 outline-none dark:bg-slate-800"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl bg-slate-100 px-3 py-3 font-semibold outline-none dark:bg-slate-800"><option value="all">All statuses</option><option value="draft">Draft</option><option value="upcoming">Upcoming</option><option value="live">Live</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button onClick={()=>{load();toast.success("Auction list refreshed")}} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold dark:border-slate-700"><FiRefreshCw/> Refresh</button></div>
 {error?<ErrorState message={error} onRetry={load}/>:filtered.length===0?<EmptyState title="No auctions found" message={q||status!=="all"?"Try another search or status filter.":"There are no auctions available yet."}/>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(a=><AuctionCard key={a._id} auction={a}/>)}</div>}</div>
}
function AuctionCard({auction:a}){return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="relative h-44 bg-slate-100 dark:bg-slate-800">{a.image?<img src={a.image} alt="" className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display="none"}}/>:<div className="grid h-full place-items-center"><FiActivity className="text-5xl text-slate-300 dark:text-slate-600"/> </div>}<div className="absolute left-4 top-4"><AuctionStatusBadge status={a.status}/></div></div><div className="space-y-5 p-5"><div><h2 className="text-xl font-black">{a.name}</h2><p className="mt-1 line-clamp-2 text-sm text-slate-500 dark:text-slate-400">{a.description||"No description provided."}</p></div><div className="grid grid-cols-2 gap-3 text-sm"><span className="flex items-center gap-2 text-slate-500"><FiCalendar/>{date(a.date)}</span><span className="flex items-center gap-2 text-slate-500"><FiDollarSign/>{money(a.minimumBid)} base</span><span className="flex items-center gap-2 text-slate-500"><FiUsers/>{a.maxTeams} teams</span><span className="flex items-center gap-2 text-slate-500"><FiActivity/>{money(a.bidIncrement)} step</span></div><Link to={`/auctions/${a._id}`} className="inline-flex items-center gap-2 text-sm font-black">View details <FiArrowRight/></Link></div></article>}
