import { Link, useNavigate, useParams } from "react-router-dom";
import { useCallback, useEffect, useState } from "react";
import { FiArrowLeft, FiCalendar, FiDollarSign, FiEdit3, FiHash, FiTrash2, FiUsers } from "react-icons/fi";
import toast from "react-hot-toast";
import { deleteAuction, getAuction } from "../api/auctionApi";
import AuctionStatusBadge from "../components/auction/AuctionStatusBadge";
import LoadingScreen from "../components/LoadingScreen";
import ErrorState from "../components/ErrorState";
import { useAuth } from "../context/AuthContext";
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n||0));
export default function AuctionDetails(){const {id}=useParams(),nav=useNavigate(),{isAdmin}=useAuth();const [a,setA]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{const r=await getAuction(id);setA(r.auction)}catch(e){setError(e.response?.data?.message||"Unable to load auction.")}finally{setLoading(false)}},[id]);useEffect(()=>load(),[load]);if(loading)return <LoadingScreen label="Loading auction..."/>;if(error)return <ErrorState message={error} onRetry={load}/>;
 const canModify=isAdmin&&!['live','completed'].includes(a.status); const remove=async()=>{if(!window.confirm(`Delete "${a.name}"? This cannot be undone.`))return;try{await deleteAuction(a._id);toast.success("Auction deleted");nav("/auctions",{replace:true})}catch(e){toast.error(e.response?.data?.message||"Unable to delete auction.")}};
 return <div className="space-y-6"><Link to="/auctions" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 dark:hover:text-white"><FiArrowLeft/> Back to auctions</Link><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="relative h-64 bg-slate-100 dark:bg-slate-800 sm:h-80">{a.image?<img src={a.image} alt={a.name} className="h-full w-full object-cover"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 to-transparent"/><div className="absolute bottom-6 left-6 right-6 text-white"><AuctionStatusBadge status={a.status}/><h1 className="mt-3 text-3xl font-black sm:text-4xl">{a.name}</h1></div></div><div className="p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:justify-between"><p className="max-w-3xl leading-7 text-slate-600 dark:text-slate-300">{a.description||"No description provided."}</p>{isAdmin&&<div className="flex gap-2"><Link to={`/admin/auctions/${a._id}/edit`} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold dark:border-slate-700 ${!canModify?'pointer-events-none opacity-40':''}`}><FiEdit3/> Edit</Link>{canModify&&<button onClick={remove} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600 dark:border-red-900"><FiTrash2/> Delete</button>}</div>}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[FiCalendar,"Auction date",new Date(a.date).toLocaleString("en-IN")],[FiDollarSign,"Starting budget",money(a.startingBudget)],[FiDollarSign,"Minimum bid",money(a.minimumBid)],[FiDollarSign,"Bid increment",money(a.bidIncrement)],[FiUsers,"Maximum teams",a.maxTeams],[FiUsers,"Players per team",a.maxPlayersPerTeam],[FiHash,"Created by",a.createdBy?.name||"Admin"]].map(([Icon,l,v])=><div key={l} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><Icon className="text-xl"/><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-400">{l}</p><p className="mt-1 font-black">{v}</p></div>)}</div></div></div></div>}
