import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthContext";
import { ThemeProvider } from "./context/ThemeContext";
import ProtectedRoute from "./components/ProtectedRoute";
import Login from "./pages/Login"; import Register from "./pages/Register"; import ForgotPassword from "./pages/ForgotPassword"; import ResetPassword from "./pages/ResetPassword";
import DashboardLayout from "./layouts/DashboardLayout"; import Dashboard from "./pages/Dashboard"; import PlaceholderPage from "./pages/PlaceholderPage";
import Auctions from "./pages/Auctions"; import AuctionDetails from "./pages/AuctionDetails"; import AuctionAccess from "./pages/AuctionAccess"; import LiveAuctions from "./pages/LiveAuctions"; import LiveAuction from "./pages/LiveAuction"; import AdminAuctionManagement from "./pages/admin/AdminAuctionManagement"; import AuctionFormPage from "./pages/admin/AuctionFormPage"; import TeamManagement from "./pages/admin/TeamManagement";
const P=({title,description})=><PlaceholderPage title={title} description={description}/>;
export default function App(){return <BrowserRouter><ThemeProvider><AuthProvider><Toaster position="top-right" toastOptions={{duration:3500}}/><Routes><Route path="/" element={<Navigate to="/dashboard" replace/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password/:token" element={<ResetPassword/>}/><Route element={<ProtectedRoute/>}><Route element={<DashboardLayout/>}><Route path="/dashboard" element={<Dashboard/>}/><Route path="/auctions" element={<Auctions/>}/><Route path="/auctions/:id" element={<AuctionDetails/>}/><Route path="/auctions/:id/access" element={<AuctionAccess/>}/><Route path="/live-auctions" element={<LiveAuctions/>}/><Route path="/live-auctions/:auctionId" element={<LiveAuction/>}/><Route path="/notifications" element={<P title="Notifications" description="Auction notifications will be connected in Group 14."/>}/><Route path="/statistics" element={<P title="Auction Statistics" description="Auction statistics will be connected in Group 14."/>}/><Route path="/profile" element={<P title="Profile" description="Manage your AuctionPro profile."/>}/><Route path="/settings" element={<P title="Settings" description="Manage application preferences and account settings."/>}/><Route element={<ProtectedRoute adminOnly />}><Route path="/admin/auctions" element={<AdminAuctionManagement/>}/><Route path="/admin/auctions/new" element={<AuctionFormPage/>}/><Route path="/admin/auctions/:id/edit" element={<AuctionFormPage edit/>}/><Route path="/admin/teams" element={<TeamManagement/>}/><Route path="/admin/players" element={<P title="Player Management" description="Player management will be connected in Group 7."/>}/><Route path="/admin/registrations" element={<P title="Registration Management" description="Registration approvals will be connected in Group 9."/>}/><Route path="/admin/auction-control" element={<P title="Auction Control" description="Live auction controls will be connected in Group 13."/>}/></Route></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></AuthProvider></ThemeProvider></BrowserRouter>}
